rules:
  MD001: true
  MD003:
    style: atx
  MD004:
    style: dash
  MD007:
    indent: 2
  MD009: true
  MD010:
    code_blocks: false
  MD012: true
  MD013:
    line_length: 120
    code_blocks: false
    tables: false
    headings: false
  MD018: true
  MD022: true
  MD024:
    siblings_only: true
  MD025:
    level: 1
    front_matter_title: ".*"
  MD026:
    punctuation: ".,;:!?"
  MD029:
    style: one
  MD030:
    ul_single: 1
    ul_multi: 1
    ol_single: 1
    ol_multi: 1
  MD033:
    allowed_elements: ["br"]
  MD034: true
  MD036: true
  MD038: true
  MD041: false
  MD046:
    style: fenced
  MD048: true

ignores:
  - node_modules/
  - .git/
  - prompts/snippets/*.sh

